format_version: 3
pipelines:
  "SLE15.SP1.Staging.A":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:A
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.B":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:B
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.C":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:C
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.D":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:D
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.E":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:E
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.F":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:F
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.G":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:G
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.H":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:H
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.S":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:S
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.V":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:V
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
  "SLE15.SP1.Staging.Y":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:Y
      STAGING_API: https://api.suse.de
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              tasks:
                - exec:
                    command: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              resources:
                - repo-checker
              tasks:
                - exec:
                    command: ./update-000product.sh
