format_version: 3
pipelines:
  SLE15.SP1.RelPkgs:
    group: SLE15.SP1.Target
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 10 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Create.Release.Packages:
        approval: manual
        resources:
        - repo-checker
        tasks:
        - script: /usr/bin/osrt-pkglistgen -A https://api.suse.de update_and_solve -p SUSE:SLE-15-SP1:GA -s target --only-release-packages --force

  SLE15.SP1.Package.Lists:
    group: SLE15.SP1.Target
    lock_behavior: unlockWhenFinished
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        whitelist:
          - SUSE:SLE-15-SP1:GA_-_standard.yaml
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Update.000product:
        resources:
        - repo-checker
        tasks:
        - script: |-
            /usr/bin/python /usr/bin/osrt-pkglistgen --apiurl https://api.suse.de --debug update_and_solve -p SUSE:SLE-15-SP1:GA -s target --force || true

  SLE15.SP1.Images:
    group: SLE15.SP1.Target
    lock_behavior: unlockWhenFinished
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        whitelist:
          - SUSE:SLE-15-SP1:GA_-_images.yaml
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Expect.Images.To.Finish:
        resources:
        - staging-bot
        tasks:
        - script: |
            export PYTHONPATH=/usr/share/openSUSE-release-tools
            git clone https://github.com/coolo/citest.git
            cd citest
            python ./verify-repo-built-successful.py -A https://api.suse.de -p SUSE:SLE-15-SP1:GA -r images

    - Release.Images.To.Test:
        approval: manual
        roles:
        - SLE
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-totest-manager
        resources:
        - staging-bot
        tasks:
        - script: |-
            for product in kiwi-templates-SLES15-JeOS \
                SLES15-SP1-Azure SLES15-SP1-Azure-BYOS \
                SLES15-SP1-Azure-Priority SLES15-SP1-Azure-Standard \
                SLES15-SP1-EC2-ECS-HVM SLES15-SP1-EC2-HVM \
                SLES15-SP1-EC2-HVM-BYOS SLES15-SP1-GCE SLES15-SP1-GCE-BYOS \
                SLES15-SP1-SAP-Azure SLES15-SP1-SAP-Azure-BYOS \
                SLES15-SP1-SAP-Azure-LI-BYOS \
                SLES15-SP1-SAP-EC2-HVM SLES15-SP1-SAP-EC2-HVM-BYOS \
                SLES15-SP1-OCI-BYOS SLES15-SP1-SAP-OCI-BYOS \
                SLES15-SP1-SAP-GCE SLES15-SP1-SAP-GCE-BYOS 000product; do
              osc -A https://api.suse.de release SUSE:SLE-15-SP1:GA $product
            done
